// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xfm_synth.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XFm_synth_CfgInitialize(XFm_synth *InstancePtr, XFm_synth_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_bus_BaseAddress = ConfigPtr->Ctrl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XFm_synth_Set_modulator_wave(XFm_synth *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFm_synth_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_MODULATOR_WAVE_DATA, Data);
}

u32 XFm_synth_Get_modulator_wave(XFm_synth *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFm_synth_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_MODULATOR_WAVE_DATA);
    return Data;
}

void XFm_synth_Set_modulator_phase(XFm_synth *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFm_synth_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_MODULATOR_PHASE_DATA, Data);
}

u32 XFm_synth_Get_modulator_phase(XFm_synth *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFm_synth_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_MODULATOR_PHASE_DATA);
    return Data;
}

void XFm_synth_Set_scale_factor(XFm_synth *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFm_synth_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_SCALE_FACTOR_DATA, Data);
}

u32 XFm_synth_Get_scale_factor(XFm_synth *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFm_synth_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_SCALE_FACTOR_DATA);
    return Data;
}

void XFm_synth_Set_carrier_wave(XFm_synth *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFm_synth_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_CARRIER_WAVE_DATA, Data);
}

u32 XFm_synth_Get_carrier_wave(XFm_synth *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFm_synth_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_CARRIER_WAVE_DATA);
    return Data;
}

void XFm_synth_Set_carrier_phase(XFm_synth *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFm_synth_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_CARRIER_PHASE_DATA, Data);
}

u32 XFm_synth_Get_carrier_phase(XFm_synth *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFm_synth_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_CARRIER_PHASE_DATA);
    return Data;
}

void XFm_synth_Set_sync(XFm_synth *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFm_synth_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_SYNC_DATA, Data);
}

u32 XFm_synth_Get_sync(XFm_synth *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFm_synth_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_SYNC_DATA);
    return Data;
}

