// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xfm_synth.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XFm_synth_CfgInitialize(XFm_synth *InstancePtr, XFm_synth_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_bus_BaseAddress = ConfigPtr->Ctrl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XFm_synth_Set_press(XFm_synth *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFm_synth_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_PRESS_DATA, Data);
}

u32 XFm_synth_Get_press(XFm_synth *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFm_synth_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_PRESS_DATA);
    return Data;
}

void XFm_synth_Set_modulator_wave(XFm_synth *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFm_synth_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_MODULATOR_WAVE_DATA, Data);
}

u32 XFm_synth_Get_modulator_wave(XFm_synth *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFm_synth_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_MODULATOR_WAVE_DATA);
    return Data;
}

void XFm_synth_Set_modulator_phase(XFm_synth *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFm_synth_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_MODULATOR_PHASE_DATA, Data);
}

u32 XFm_synth_Get_modulator_phase(XFm_synth *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFm_synth_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_MODULATOR_PHASE_DATA);
    return Data;
}

void XFm_synth_Set_scale_factor(XFm_synth *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFm_synth_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_SCALE_FACTOR_DATA, Data);
}

u32 XFm_synth_Get_scale_factor(XFm_synth *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFm_synth_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_SCALE_FACTOR_DATA);
    return Data;
}

void XFm_synth_Set_carrier_wave(XFm_synth *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFm_synth_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_CARRIER_WAVE_DATA, Data);
}

u32 XFm_synth_Get_carrier_wave(XFm_synth *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFm_synth_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_CARRIER_WAVE_DATA);
    return Data;
}

void XFm_synth_Set_carrier_phase(XFm_synth *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFm_synth_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_CARRIER_PHASE_DATA, Data);
}

u32 XFm_synth_Get_carrier_phase(XFm_synth *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFm_synth_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_CARRIER_PHASE_DATA);
    return Data;
}

void XFm_synth_Set_user_writing(XFm_synth *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFm_synth_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_USER_WRITING_DATA, Data);
}

u32 XFm_synth_Get_user_writing(XFm_synth *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFm_synth_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_USER_WRITING_DATA);
    return Data;
}

void XFm_synth_Set_attackMaximum(XFm_synth *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFm_synth_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_ATTACKMAXIMUM_DATA, Data);
}

u32 XFm_synth_Get_attackMaximum(XFm_synth *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFm_synth_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_ATTACKMAXIMUM_DATA);
    return Data;
}

void XFm_synth_Set_attackDuration(XFm_synth *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFm_synth_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_ATTACKDURATION_DATA, Data);
}

u32 XFm_synth_Get_attackDuration(XFm_synth *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFm_synth_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_ATTACKDURATION_DATA);
    return Data;
}

void XFm_synth_Set_decayDuration(XFm_synth *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFm_synth_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_DECAYDURATION_DATA, Data);
}

u32 XFm_synth_Get_decayDuration(XFm_synth *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFm_synth_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_DECAYDURATION_DATA);
    return Data;
}

void XFm_synth_Set_sustainAmplitude(XFm_synth *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFm_synth_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_SUSTAINAMPLITUDE_DATA, Data);
}

u32 XFm_synth_Get_sustainAmplitude(XFm_synth *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFm_synth_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_SUSTAINAMPLITUDE_DATA);
    return Data;
}

void XFm_synth_Set_sustainDuration(XFm_synth *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFm_synth_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_SUSTAINDURATION_DATA, Data);
}

u32 XFm_synth_Get_sustainDuration(XFm_synth *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFm_synth_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_SUSTAINDURATION_DATA);
    return Data;
}

void XFm_synth_Set_releaseDuration(XFm_synth *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFm_synth_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_RELEASEDURATION_DATA, Data);
}

u32 XFm_synth_Get_releaseDuration(XFm_synth *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFm_synth_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFM_SYNTH_CTRL_BUS_ADDR_RELEASEDURATION_DATA);
    return Data;
}

